# Generated by Django 5.0.2 on 2024-05-12 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompt_agent', '0001_initial'),
        ('vulnerabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('SM', 'Stats per Model'), ('IR', 'Indirect Reference'), ('IP', 'Ignore Previous Instructions'), ('DR', 'Direct'), ('SV', 'Security Violating'), ('PE', 'Privilege Escalation')], max_length=2)),
                ('metric1', models.FloatField()),
                ('metric2', models.FloatField()),
                ('metric3', models.FloatField()),
                ('metric4', models.FloatField()),
                ('metric5', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompt_agent.llmmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySumCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=7)),
                ('usage', models.PositiveBigIntegerField(default=0)),
                ('errors', models.PositiveBigIntegerField(default=0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompt_agent.llmmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rule', models.TextField()),
                ('language', models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('JV', 'Java'), ('RB', 'Ruby'), ('PH', 'PHP'), ('GO', 'Go'), ('C', 'C'), ('CP', 'C++'), ('C#', 'C#'), ('TS', 'TypeScript'), ('SW', 'Swift'), ('KT', 'Kotlin'), ('SC', 'Scala'), ('RS', 'Rust'), ('SH', 'Shell'), ('OC', 'Objective-C'), ('BS', 'Bash'), ('SQ', 'SQL'), ('HT', 'HTML'), ('CS', 'CSS'), ('OT', 'Other')], default='C', max_length=3)),
                ('meta_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.analyzer')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.vulnerability')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompt_agent.llmmodel')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.rule')),
            ],
        ),
    ]
