# Generated by Django 5.0.2 on 2024-04-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
