# Generated by Django 5.0.2 on 2024-04-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_rule_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='language',
            field=models.CharField(default='c', max_length=100),
            preserve_default=False,
        ),
    ]
