# Generated by Django 5.0.1 on 2024-01-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='api_type',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='POST', max_length=100),
            preserve_default=False,
        ),
    ]
