# Generated by Django 5.0.1 on 2024-01-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeanalyzer', '0002_engine_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='api_data',
            field=models.CharField(choices=[('JSON', 'JSON'), ('FORMDATA', 'FORMDATA')], default='JSON', max_length=100),
            preserve_default=False,
        ),
    ]
