# Generated by Django 5.0.1 on 2024-01-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeanalyzer', '0003_engine_api_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='api_params',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
    ]
