# Generated by Django 5.0.1 on 2024-01-28 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeanalyzer', '0004_engine_api_params'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='InsecurePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('cwe_id', models.CharField(max_length=100)),
                ('rule', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=100)),
                ('regexes', models.JSONField(blank=True, null=True)),
                ('pattern_id', models.CharField(blank=True, max_length=100, null=True)),
                ('public', models.BooleanField(default=True)),
                ('engine', models.CharField(choices=[('WEGGLI', 'WEGGLI'), ('REGEX', 'REGEX'), ('SEMGREP', 'SEMGREP')], max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
