# Generated by Django 5.0.1 on 2024-01-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptdispatcher', '0002_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='model',
            field=models.CharField(choices=[('ANYSCALE::meta-llama/Llama-2-13b-chat-hf', 'ANYSCALE::meta-llama/Llama-2-13b-chat-hf')], max_length=100),
        ),
        migrations.CreateModel(
            name='RecordedIssuws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=100)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promptdispatcher.results')),
            ],
        ),
    ]
