# Generated by Django 5.0.1 on 2024-01-27 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptdispatcher', '0003_alter_llm_model_recordedissuws'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='name',
            field=models.CharField(default='Llama2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llm',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
