# Generated by Django 5.0.1 on 2024-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptdispatcher', '0005_results_benchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('meta-llama', 'meta-llama')], max_length=100)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
