# Generated by Django 5.0.1 on 2024-01-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptdispatcher', '0006_llmsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmsummary',
            name='model_type',
            field=models.CharField(choices=[('meta-llama', 'meta-llama')], max_length=100, unique=True),
        ),
    ]
