# Generated by Django 5.0.2 on 2024-05-16 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vulnerabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rule', models.TextField()),
                ('language', models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('JV', 'Java'), ('RB', 'Ruby'), ('PH', 'PHP'), ('GO', 'Go'), ('C', 'C'), ('CP', 'C++'), ('C#', 'C#'), ('TS', 'TypeScript'), ('SW', 'Swift'), ('KT', 'Kotlin'), ('SC', 'Scala'), ('RS', 'Rust'), ('SH', 'Shell'), ('OC', 'Objective-C'), ('BS', 'Bash'), ('SQ', 'SQL'), ('HT', 'HTML'), ('CS', 'CSS'), ('OT', 'Other')], default='C', max_length=3)),
                ('meta_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_agent.analyzer')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.vulnerability')),
            ],
        ),
    ]
