# Generated by Django 5.0.2 on 2024-05-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
